Add endpoint_type and vpc_endpoint_id variables and identifiers to enable private transfer
schubergphilis/terraform-aws-mcaf-transfer pull request #3
Opened 2019-10-24 07:52 UTC by stefanwb

2019-12-03 16:48 UTC, marwinbaumannsbp submitted a review, later dismissed

2019-12-03 16:56 UTC, shoekstra requested changes

2019-12-03 16:56 UTC, shoekstra commented on variables.tf
> +  default     = ""
Can we use `null` instead of `""` for empty defaults please

2019-12-03 16:56 UTC, shoekstra commented on main.tf
> +  depends_on = [aws_iam_role.default]
Can we move this line above `endpoint_details` so it's with the other fields please?

`depends_upon` should be the last field in the group of fields.

2019-12-04 10:22 UTC, marwinbaumannsbp approved these changes
Included in new commit

2019-12-04 10:34 UTC, marwinbaumannsbp submitted a review, later dismissed
included changes

2019-12-04 10:41 UTC, shoekstra approved these changes

2019-12-04 10:41 UTC, merged